name: tests
on: [push, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Prepare .env file
        run: cp .env.test .env
      - name: Run tests
        run: flutter test
      - name: Clean up .env file
        run: rm .env
